### ISSUE TITLE
ドメイン周りの設定

### ISSUE THREAD

**Issue by integral0523** [ut-code/kf73#5]
kf73.utcode.net

**Comment by chelproc** [comment]
とりあえず設定完了しました

![image](https://user-images.githubusercontent.com/45363260/201953451-ea30c602-9ab4-402d-9c2a-b84d8ad5fe22.png)

GitHub 側から DNS の確認が取れたら完了

**Comment by integral0523** [comment]
できました！
ありがとう〜

閉じます
